spring:
  security:
    filter:
      order: 10
  datasource:
    url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_USER }}
    password: ${{ secrets.DB_PASS }}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${{ secrets.JWT_SECRET_KEY }}
  expiration: 16000

server:
  port: 8080
