name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
      
      run: mvn -B package --file pom.xml
      
    - name: Run Tests
      run: mvn test
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
        
    # 3. Construir y enviar la imagen a Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: thewadjet/auth-and-identity-domain:latest

    # 4. Conectar y desplegar en EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          # Verificar si Docker está instalado, si no, instalarlo
          if ! command -v docker &> /dev/null; then
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            sudo systemctl enable docker
          fi
      
          # Esperar un momento para asegurarse de que Docker esté listo
          sleep 10
        
          sudo docker pull thewadjet/auth-and-identity-domain:latest
          sudo docker stop auth-and-identity-domain || true
          sudo docker rm auth-and-identity-domain || true
          sudo docker run -d --name auth-and-identity-domain -p 8000:8000 thewadjet/auth-and-identity-domain:latest
